In [37]:
# 데이터 생성
import pandas as pd

food = pd.DataFrame({
    "메뉴": ["김밥", "비빔밥", "자장면", "우동", "김밥", "자장면", "김밥"],
    "가격": [3000, 7000, 5500, 5500, 3500, 6000, 4000],
    "분류": ["한식", "한식", "중식", "일식", "한식", "중식", "한식"]
})
food

    메뉴    가격  분류
0   김밥  3000  한식
1  비빔밥  7000  한식
2  자장면  5500  중식
3   우동  5500  일식
4   김밥  3500  한식
5  자장면  6000  중식
6   김밥  4000  한식

In [38]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   분류      7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [39]:
food.head()     # 기본 5개 데이터 출력

    메뉴    가격  분류
0   김밥  3000  한식
1  비빔밥  7000  한식
2  자장면  5500  중식
3   우동  5500  일식
4   김밥  3500  한식

In [40]:
food.tail(3)      # 끝에서 3개 데이터 출력

    메뉴    가격  분류
4   김밥  3500  한식
5  자장면  6000  중식
6   김밥  4000  한식

In [41]:
food.describe()   # 수지형(기본) 숫자만 나옴

                가격
count     7.000000
mean   4928.571429
std    1455.694892
min    3000.000000
25%    3750.000000
50%    5500.000000
75%    5750.000000
max    7000.000000

In [42]:
food.describe(include='number')

                가격
count     7.000000
mean   4928.571429
std    1455.694892
min    3000.000000
25%    3750.000000
50%    5500.000000
75%    5750.000000
max    7000.000000

In [43]:
food.describe(include=object)   # 문자형  / 문자를 보고 싶은면 같은 글자 빈도수

        메뉴  분류
count    7   7
unique   4   3
top     김밥  한식
freq     3   4

In [44]:
# 고유한 값의 개수 - value_counts()
food["메뉴"].value_counts()
food["분류"].value_counts()

분류
한식    4
중식    2
일식    1
Name: count, dtype: int64

In [45]:
# 할인가 칼럼 추가 - 할인 10%

discount = 0.1
food['할인가'] = food['가격'] * (1 - discount)
food

# 자료형 변환 - astype(자료형)

food['할인가'] = food['할인가'].astype('int64') 
food

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [46]:
# CSV 파일 변환
import pandas as pd

food.to_csv("datas/food.csv", index=False)


df = pd.read_csv("datas/food.csv")
df

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [47]:
# 정렬 - 오름차순, 내림차순 정렬 -> sort_values()
# df = df.sort_values("가격", ascending=True)


# inplace=True, 즉시 적용
# 가격을 오름차순 정렬
df.sort_values("가격", ascending=True, inplace=True)
df

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
4   김밥  3500  한식  3150
6   김밥  4000  한식  3600
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
5  자장면  6000  중식  5400
1  비빔밥  7000  한식  6300

In [48]:
# 가격을 높은 순으로 정렬 - 내림차순
df.sort_values("가격", ascending=False, inplace=True)
df

    메뉴    가격  분류   할인가
1  비빔밥  7000  한식  6300
5  자장면  6000  중식  5400
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
6   김밥  4000  한식  3600
4   김밥  3500  한식  3150
0   김밥  3000  한식  2700

In [49]:
# 정렬 초기화 - sort_index()
df =df.sort_index()
df

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [50]:
# 조건 검색
# 메뉴가 자장면인 음식 정보 
result1 = (df['메뉴'] == '자장면')
print(df[result1])

    메뉴    가격  분류   할인가
2  자장면  5500  중식  4950
5  자장면  6000  중식  5400

In [51]:
# 가격이 4천원 미만인 음식 정보
result2 = (df['가격'] < 4000)
print(df[result2])

   메뉴    가격  분류   할인가
0  김밥  3000  한식  2700
4  김밥  3500  한식  3150

In [57]:
# 메뉴가 자장면 이면서, 가격이 6천원 이상인 음식 정보(동시 만족)

result3 = (df['메뉴'] =='자장면') & (df['가격'] >= 6000)
print(df[result3])

    메뉴    가격  분류   할인가
5  자장면  6000  중식  5400

In [58]:
# 메뉴가 자장면 이거나, 가격이 6천원 이상인 음식 정보 

result4 = (df['메뉴'] =='자장면') | (df['가격'] >= 6000)
print(df[result4])

    메뉴    가격  분류   할인가
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
5  자장면  6000  중식  5400

In [62]:
# 분류가 중식이 아닌 음식을 검색하세요

result5 = (df['분류'] != '중식')
print(df[result5])

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
6   김밥  4000  한식  3600